services:
  # PHP + APACHE
  # APP (Production-like environment with Nginx + PHP-FPM)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: differenziali_app
    ports:
      - "80:80"
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: mio_db
      DB_USERNAME: root
      DB_PASSWORD: root
    networks:
      - dev_network

  # DATABASE (MariaDB)
  db:
    image: mariadb:10.11
    container_name: php_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mio_db
    networks:
      - dev_network

  # INTERFACCIA DATABASE (Sostituisce phpMyAdmin di XAMPP)
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: php_pma
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db # Deve corrispondere al nome del servizio database sopra
    networks:
      - dev_network

networks:
  dev_network:
    driver: bridge