services:
  - type: web
    name: differenziali-app
    runtime: docker
    plan: free
    region: frankfurt
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "true"
      - key: LOG_CHANNEL
        value: stderr
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: differenziali-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: differenziali-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: differenziali-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: differenziali-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: differenziali-db
          property: password

databases:
  - name: differenziali-db
    plan: free
    region: frankfurt
    databaseName: differenziali
    user: admin
